config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'welcome#index'
  get '/signin', to: 'sessions#new'
  get '/signup', to: 'users#new'
  resources :users, except: [:new]
  resources :sessions, only: [:create]
  post '/logout', to: 'sessions#destroy'
  resources :rooms, only: [:show, :new, :create, :update]
  resources :posts, only: [:new, :create, :destroy]
  resources :topics, only: [:index]
  get '/statistics', to: 'statistics#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string
#  password_digest :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true
  validates :password, length: {in: 3..16}, on: :create

  has_many :memberships
  has_many :rooms, through: :memberships
  has_many :posts, through: :memberships




  def average_posts_per_day  
    days_active = (Time.now - self.created_at)/86400
    (days_active / self.post_count).round(1)
  end

  def room_count
  	self.rooms.count
  end

  def post_count
    self.posts.count
  end

  def narcissism
    allposts = self.posts.map{|post| post.content }.join(" ").upcase
    allposts.split(" ").count("I")
  end

  def is_most_narcissistic_user?
    self.narcissism == User.all.map {|user| user.narcissism}.sort.last
  end

  def favorite_room
  self.rooms.sort{|a,b| a.memberships.select{|membership| membership.user_id = self.id}.count <=> b.memberships.select{|membership| membership.user_id = self.id}.count}.first.name
  end

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :check_for_cancel, only: [:update]

  def new
    redirect_to current_user unless !logged_in?
    @user = User.new
  end

  def create
    if !User.find_by(username: "deleted_user")
       User.create(username: 'deleted_user', password: 'password')
    end
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @room = Room.new
  end

  def edit
    find_user_by_session_id
  end

  def update
    find_user_by_session_id
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private

  def check_for_cancel
    if params[:commit] == "Cancel"
      redirect_to user_path
    end
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def require_login
    redirect_to '/signin' unless session.include?(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @user do |f| %>
  <%= f.label 'Username:' %>
  <br>
  <%= f.text_field :username %>
  <br><br>
  <%= f.label 'Password:' %>
  <br>
  <%= f.password_field :password %>
  <br><br>
  <%= f.label 'Confirm Password:' %>
  <br>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit 'Edit User' %>
  <%= button_to 'Cancel', @user, method: 'get' %>
<% end %>

app/views/users/new.html.erb
<h1>Create New Account</h1>
<% if @user.errors.any? %>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @user do |f| %>
  <%= f.label 'Username:' %>
  <br>
  <%= f.text_field :username %>
  <br><br>
  <%= f.label 'Password:' %>
  <br>
  <%= f.password_field :password %>
  <br><br>
  <%= f.label 'Confirm Password:' %>
  <br>
  <%= f.password_field :password_confirmation %>
  <br><br>
  <%= f.submit 'Create User' %>
<% end %>
<h3>Already have an account?
<%= link_to 'Sign In', '/signin' %></h3>

app/views/users/show.html.erb
<% if session[:user_id] == @user.id %>
  <h1>Hi, <%= @user.username %></h1>
  <h4><%= link_to "Browse Rooms", topics_path %></h4>

  <% if @room.errors.any? %>
  <ul>
    <% @room.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= form_for @room do |f| %>
    <%= f.label 'Topics:' %>
    <%= f.select :topic_id, Topic.all.map {|element| [element.name, element.id, name: element.name]} %>
    <br><br>
    <%= f.label 'Room Name:' %>
    <%= f.text_field :name %>
    <br><br>
    <%= f.submit 'Create a Room' %>
  <% end %>
  <br /><br />
  <bold>Most Narcissistic Room:</bold> <%= Room.most_narcissistic %>
  <br /><br />
  <h2>Your Room List:</h2>
  <% if @user.rooms.empty? %>
    You have not joined any rooms!
    <br>
  <% else %>
    <ul>
      <% @user.rooms.each do |room| %>
        <li><%= link_to room.name, room_path(room) %></li>
      <% end %>
    <% end %>
  </ul>
  <br>
  <%= link_to 'Edit Your Account', edit_user_path(@user) %>
  <br><br>
  <%= link_to 'See Site Statistics', '/statistics' %>
  <br><br>
  <%= button_to 'Logout', '/logout' %>
<% else %>
  <h1><%= @user.username %>'s Profile</h1>
  <h2>Their Room List:</h2>
  <% if @user.rooms.empty? %>
    The user does not belong to any rooms!
  <% else %>
    <ul>
      <% @user.rooms.each do |room| %>
        <li><%= link_to room.name, room_path(room) %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>